"""
Refine the `Instructor` role and de-scope teachers from `Academics User`.

Run with:
    bench --site app.makkobillischool.com execute \
        mbs.migrate_teacher_permissions.run --kwargs "{'dry_run': True}"

or paste into `bench --site app.makkobillischool.com console` and call run().

ALWAYS run with dry_run=True first and read the diff it prints.

Design decisions this implements (agreed 2026-09-17):
  * No new role. The existing `Instructor` role is reshaped in place.
  * `Academics User` is removed from real teachers; the 17 leadership
    accounts and the unlinked-but-active staff keep it.
  * Reads are scoped with Permission Query server scripts following the
    site's existing house pattern (set `conditions` only when the role
    matches, leave empty otherwise, so multiple scripts AND cleanly).
  * Late/sick/permission records: any teacher may READ them for students
    in their own sections; only the HOMEROOM teacher of the student's
    section may CREATE or MODIFY them. Enforced by validate hooks, since
    permission queries scope reads only.
  * Appeals stay with Education Manager / System Manager.
  * `Teacher Evaluation.reviewer` moves to permlevel 1 so teachers can
    read their own ratings without ever seeing who submitted them.
"""

import json

import frappe

# --------------------------------------------------------------------------
# 1. The target permission matrix for the `Instructor` role
# --------------------------------------------------------------------------
# (read, write, create, delete, submit, cancel, amend, report, export, if_owner)
# Anything not listed here gets NO Instructor permission at all.

INSTRUCTOR_PERMS = {
    # --- results -----------------------------------------------------------
    # write/create kept so teachers can enter marks; scoped to taught pairs
    # by the permission query. delete never.
    "Student Term Subject Result": dict(read=1, write=1, create=1, delete=0, submit=0, report=1, export=1),
    # was write+create+delete via Instructor — now read-only. Reports are
    # generated by the Result Calculation Tool, not by hand.
    "Student Term Report": dict(read=1, report=1, export=1),
    "Student Year Report": dict(read=1, report=1, export=1),

    # --- people & sections (read-only, row-scoped) -------------------------
    "Student": dict(read=1, report=1),
    "Student Group": dict(read=1, report=1),
    "Instructor": dict(read=1),
    "Course": dict(read=1),
    "Program": dict(read=1),
    "Academic Year": dict(read=1),
    "Academic Term": dict(read=1),
    "Room": dict(read=1),
    "Holiday List": dict(read=1),

    # --- timetable (was read/write/create/delete via Academics User) --------
    "Course Schedule": dict(read=1, report=1),

    # --- attendance --------------------------------------------------------
    # create + write + submit, no delete/cancel/amend: a teacher may fix a
    # draft, but a submitted register is corrected on the desk.
    "Student Attendance": dict(read=1, write=1, create=1, delete=0, submit=1, report=1, export=1),

    # --- late / sick / permission -----------------------------------------
    # if_owner removed so a teacher can see their whole section's history,
    # not just rows they typed. Creation is gated to homeroom by the
    # validate hooks installed below.
    "Student Late Day": dict(read=1, write=1, create=1, delete=0, submit=1, report=1, export=1),
    "Student Sick Day": dict(read=1, write=1, create=1, delete=0, submit=1, report=1, export=1),
    "Student Permission Leave": dict(read=1, write=1, create=1, delete=0, submit=1, report=1, export=1),
    "Student Leave Application": dict(read=1, report=1),

    # --- student records (delete revoked across the board) -----------------
    "Student Log": dict(read=1, write=1, create=1, delete=0, report=1),
    "Student Activity": dict(read=1, write=1, create=1, delete=0, report=1),
    "Student Incident": dict(read=1, write=1, create=1, delete=0, report=1),
    "Student Discipline Incident": dict(read=1, write=1, create=1, delete=0, report=1),
    "Student Evaluation": dict(read=1, write=1, create=1, delete=0, if_owner=1, report=1),

    # --- messaging ---------------------------------------------------------
    # delete revoked entirely, including on their own threads.
    "Teacher Parent Message": dict(read=1, write=1, create=1, delete=0, report=1),

    # --- evaluations of the teacher ---------------------------------------
    # read only, scoped to their own rows; `reviewer` sits at permlevel 1
    # which this role is deliberately not granted.
    "Teacher Evaluation": dict(read=1, report=1),

    # --- notifications -----------------------------------------------------
    "App Notification": dict(read=1),
}

PERM_FIELDS = (
    "read", "write", "create", "delete", "submit", "cancel", "amend",
    "report", "export", "import", "share", "print", "email", "if_owner",
)

# Doctypes the Instructor role currently touches that must lose it entirely.
REVOKE_INSTRUCTOR_ENTIRELY: list[str] = []  # populated at runtime by diffing

# --------------------------------------------------------------------------
# 2. Permission query scripts
# --------------------------------------------------------------------------
# Shared preamble. A user is treated as a "scoped teacher" only when they
# hold Instructor and none of the elevated roles — so leadership, the
# registrar and System Manager are never narrowed by these scripts, and
# the existing Scholarship Supervisor scripts still AND in cleanly.

PREAMBLE = """
user_roles = set(frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role"))
ELEVATED = {"System Manager", "Education Manager", "Director", "Academics User", "DD Student Registrar"}
if "Instructor" in user_roles and not (user_roles & ELEVATED):
    instructor = frappe.db.get_value("Instructor", {"custom_username": frappe.session.user}, "name")
    if not instructor:
        conditions = "1=0"
    else:
        ins = frappe.db.escape(instructor)
"""

# Groups the teacher teaches or is homeroom of.
MY_GROUPS = """(
            SELECT sg.name FROM `tabStudent Group` sg
            WHERE sg.disabled = 0 AND (
                sg.custom_homeroom_teacher = {ins}
                OR sg.name IN (
                    SELECT sgi.parent FROM `tabStudent Group Instructor` sgi
                    WHERE sgi.instructor = {ins}
                )
            )
        )"""

# Students inside those groups.
MY_STUDENTS = """(
            SELECT sgs.student FROM `tabStudent Group Student` sgs
            WHERE sgs.active = 1 AND sgs.parent IN {my_groups}
        )""".replace("{my_groups}", MY_GROUPS)


def _student_scoped(table: str, field: str = "student") -> str:
    """Restrict a doctype to students in the teacher's own sections."""
    return (
        PREAMBLE
        + f'        conditions = "`tab{table}`.{field} IN " + """{MY_STUDENTS}""".format(ins=ins)\n'
    )


PERMISSION_QUERIES: dict[str, str] = {
    "Student": PREAMBLE
    + f'        conditions = "`tabStudent`.name IN " + """{MY_STUDENTS}""".format(ins=ins)\n',

    "Student Group": PREAMBLE
    + f'        conditions = "`tabStudent Group`.name IN " + """{MY_GROUPS}""".format(ins=ins)\n',

    "Course Schedule": PREAMBLE
    + '        conditions = ("(`tabCourse Schedule`.instructor = " + ins + '
    + f'" OR `tabCourse Schedule`.student_group IN " + """{MY_GROUPS}""".format(ins=ins) + ")")\n',

    # Marks: the pairs they actually teach, plus anything they examined,
    # plus the whole of any section they are homeroom teacher of.
    "Student Term Subject Result": PREAMBLE
    + '        conditions = ("("'
    + '\n            "`tabStudent Term Subject Result`.examiner = " + ins + " OR "'
    + '\n            "`tabStudent Term Subject Result`.student_group IN ('
    + "SELECT sg.name FROM `tabStudent Group` sg WHERE sg.disabled = 0 "
    + 'AND sg.custom_homeroom_teacher = " + ins + ") OR "'
    + '\n            "EXISTS (SELECT 1 FROM `tabCourse Schedule` cs WHERE cs.instructor = " + ins + " '
    + "AND cs.course = `tabStudent Term Subject Result`.subject "
    + 'AND cs.student_group = `tabStudent Term Subject Result`.student_group)"'
    + '\n            ")")\n',

    "Student Term Report": _student_scoped("Student Term Report"),
    "Student Year Report": _student_scoped("Student Year Report"),
    "Student Attendance": _student_scoped("Student Attendance"),
    "Student Late Day": _student_scoped("Student Late Day"),
    "Student Sick Day": _student_scoped("Student Sick Day"),
    "Student Permission Leave": _student_scoped("Student Permission Leave"),
    "Student Leave Application": _student_scoped("Student Leave Application"),
    "Student Log": _student_scoped("Student Log"),
    "Student Activity": _student_scoped("Student Activity"),
    "Student Incident": _student_scoped("Student Incident"),
    "Student Discipline Incident": _student_scoped("Student Discipline Incident"),

    # Own threads only — keyed on `teacher`, not `owner`, so a message an
    # admin created on a teacher's behalf still reaches them.
    "Teacher Parent Message": PREAMBLE
    + '        conditions = "`tabTeacher Parent Message`.teacher = " + frappe.db.escape(frappe.session.user)\n',

    # Own ratings only. Reviewer identity is withheld by permlevel, not here.
    "Teacher Evaluation": PREAMBLE
    + '        conditions = "`tabTeacher Evaluation`.instructors = " + ins\n',
}

# --------------------------------------------------------------------------
# 3. Homeroom-only write enforcement
# --------------------------------------------------------------------------
# Permission queries scope reads only, so creation/modification of the three
# attendance-event doctypes is gated here instead. Leadership is exempt.

HOMEROOM_GUARD = """
user_roles = set(frappe.db.get_all("Has Role", filters={"parent": frappe.session.user}, pluck="role"))
ELEVATED = {"System Manager", "Education Manager", "Director", "Academics User", "DD Student Registrar"}
if "Instructor" in user_roles and not (user_roles & ELEVATED):
    instructor = frappe.db.get_value("Instructor", {"custom_username": frappe.session.user}, "name")
    homeroom_groups = frappe.db.get_all(
        "Student Group",
        filters={"custom_homeroom_teacher": instructor, "disabled": 0},
        pluck="name",
    ) if instructor else []
    allowed = False
    if homeroom_groups:
        allowed = bool(frappe.db.exists(
            "Student Group Student",
            {"parent": ["in", homeroom_groups], "student": doc.student, "active": 1},
        ))
    if not allowed:
        frappe.throw(
            "Only the homeroom teacher of this student's section can record or change this.",
            title="Homeroom teachers only",
        )
"""

HOMEROOM_GUARDED_DOCTYPES = [
    "Student Late Day",
    "Student Sick Day",
    "Student Permission Leave",
]

SCRIPT_PREFIX = "MBS Staff -"


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def _current_instructor_perms() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for table in ("Custom DocPerm", "DocPerm"):
        rows = frappe.db.get_all(
            table,
            filters={"role": "Instructor", "permlevel": 0},
            fields=["parent"] + list(PERM_FIELDS),
        )
        for r in rows:
            out.setdefault(r["parent"], {k: r.get(k) or 0 for k in PERM_FIELDS})
    return out


def _set_perm(doctype: str, spec: dict, dry_run: bool) -> str | None:
    """Write one Custom DocPerm row for the Instructor role."""
    target = {f: int(spec.get(f, 0)) for f in PERM_FIELDS}
    target["read"] = int(spec.get("read", 1))

    existing = frappe.db.get_value(
        "Custom DocPerm",
        {"parent": doctype, "role": "Instructor", "permlevel": 0},
        "name",
    )
    if existing:
        before = frappe.db.get_value("Custom DocPerm", existing, list(PERM_FIELDS), as_dict=True)
        changed = {f: (before.get(f), target[f]) for f in PERM_FIELDS if int(before.get(f) or 0) != target[f]}
        if not changed:
            return None
        if not dry_run:
            frappe.db.set_value("Custom DocPerm", existing, target)
        return f"  UPDATE {doctype}: " + ", ".join(f"{f} {a}->{b}" for f, (a, b) in changed.items())

    if not dry_run:
        doc = frappe.get_doc({
            "doctype": "Custom DocPerm",
            "parent": doctype,
            "parenttype": "DocType",
            "parentfield": "permissions",
            "role": "Instructor",
            "permlevel": 0,
            **target,
        })
        doc.insert(ignore_permissions=True)
    return f"  CREATE {doctype}: " + ", ".join(f"{f}={v}" for f, v in target.items() if v)


def _upsert_script(name: str, script_type: str, doctype: str, script: str,
                   dry_run: bool, event: str | None = None) -> str:
    full_name = f"{SCRIPT_PREFIX} {name}"
    existing = frappe.db.exists("Server Script", full_name)
    payload = {
        "script_type": script_type,
        "reference_doctype": doctype,
        "script": script,
        "disabled": 0,
    }
    if event:
        payload["doctype_event"] = event

    if existing:
        if dry_run:
            return f"  UPDATE script {full_name}"
        doc = frappe.get_doc("Server Script", full_name)
        doc.update(payload)
        doc.save(ignore_permissions=True)
        return f"  UPDATE script {full_name}"

    if dry_run:
        return f"  CREATE script {full_name} ({script_type} on {doctype})"
    doc = frappe.get_doc({"doctype": "Server Script", "name": full_name, **payload})
    doc.insert(ignore_permissions=True)
    return f"  CREATE script {full_name} ({script_type} on {doctype})"


def _reviewer_permlevel(dry_run: bool) -> str:
    """Move Teacher Evaluation.reviewer to permlevel 1 and grant it to admins."""
    lines = []
    ps = frappe.db.exists("Property Setter", {
        "doc_type": "Teacher Evaluation", "field_name": "reviewer", "property": "permlevel",
    })
    if not ps:
        lines.append("  SET Teacher Evaluation.reviewer -> permlevel 1")
        if not dry_run:
            frappe.get_doc({
                "doctype": "Property Setter",
                "doctype_or_field": "DocField",
                "doc_type": "Teacher Evaluation",
                "field_name": "reviewer",
                "property": "permlevel",
                "property_type": "Int",
                "value": "1",
            }).insert(ignore_permissions=True)

    for role in ("System Manager", "Education Manager"):
        if not frappe.db.exists("Custom DocPerm", {
            "parent": "Teacher Evaluation", "role": role, "permlevel": 1,
        }):
            lines.append(f"  GRANT permlevel 1 read on Teacher Evaluation to {role}")
            if not dry_run:
                frappe.get_doc({
                    "doctype": "Custom DocPerm",
                    "parent": "Teacher Evaluation",
                    "parenttype": "DocType",
                    "parentfield": "permissions",
                    "role": role,
                    "permlevel": 1,
                    "read": 1,
                    "write": 1,
                }).insert(ignore_permissions=True)
    return "\n".join(lines)


def _teachers_to_destaff() -> list[str]:
    """Users who should lose `Academics User`: classroom teachers with a
    linked Instructor record and no elevated role. 103 accounts as of
    2026-09-17.

    Deliberately NOT included, per decisions taken 2026-09-17:
      * the 17 leadership accounts (Director / Education Manager /
        System Manager / DD Student Registrar) — excluded by the NOT IN;
      * 8 staff with Employee designation "Teacher" but no Instructor
        record — they keep the role so they don't lose working access
        before someone links them;
      * 6 non-teaching staff with Employee records (School Nurse, Unit
        Leader, Department Head, three vice-directors) — real staff;
      * `sintayehu@m.b.s` (HR / Accounts) — needs student data for fee
        and scholarship work.
    All four groups are excluded simply by requiring a linked Instructor
    record, except the leadership NOT IN clause.
    """
    return frappe.db.sql_list("""
        SELECT DISTINCT u.name
        FROM `tabUser` u
        JOIN `tabHas Role` h ON h.parent = u.name AND h.role = 'Academics User'
        JOIN `tabInstructor` i ON i.custom_username = u.name
        WHERE u.enabled = 1
          AND u.name NOT IN (
              SELECT parent FROM `tabHas Role`
              WHERE parenttype = 'User'
                AND role IN ('Director','Education Manager','System Manager','DD Student Registrar')
          )
    """)


# Second accounts belonging to teachers who already have a properly linked
# account under a different address, plus one shared departmental login.
# They lose `Academics User` but stay enabled, so if any turns out to be
# someone's real login they can still sign in — just without staff rights.
DUPLICATE_ACCOUNTS = [
    "addisu_kinfu@m.b.s",
    "aliyi.abu@m.b.s",            # -> aliyiabu07@gmail.com
    "dagi.tassew74@gmail.com",    # -> dagim.tahir@m.b.s
    "ferdowse.mohammed@m.b.s",    # -> fordosa.mohammed@m.b.s
    "g1mat@m.b.s",                # shared "G1 MAT Teacher" login
    "haymanot.andualem@m.b.s",    # -> hayimanot.andualem@m.b.s
    "meskerem.lema@m.b.s",        # -> meskilema0@gmail.com
    "mohammed.abdo@m.b.s",
    "rosa.abreham@m.b.s",         # -> roza.abreham@m.b.s
    "tamiru.demissie@m.b.s",
    "tegenu.derersa@m.b.s",       # -> tegenud12@gmail.com
    "yohannes.nigussie@m.b.s",    # -> yohannesn079@gmail.com
]

EXTRA_DESTAFF = DUPLICATE_ACCOUNTS + [
    # Student account that should never have held a staff role.
    # Already removed via MCP on 2026-09-17; listed for completeness and
    # so a re-run is a no-op rather than a surprise.
    "M2/33467/18@m.b.s",
]


def run(dry_run: bool = True, destaff: bool = True):
    log: list[str] = []
    mode = "DRY RUN — nothing written" if dry_run else "APPLYING CHANGES"
    log.append(f"=== {mode} ===\n")

    # 1. permissions -------------------------------------------------------
    log.append("--- Instructor role permissions ---")
    before = _current_instructor_perms()
    for doctype, spec in INSTRUCTOR_PERMS.items():
        line = _set_perm(doctype, spec, dry_run)
        if line:
            log.append(line)

    stale = sorted(set(before) - set(INSTRUCTOR_PERMS))
    for doctype in stale:
        log.append(f"  REVOKE Instructor entirely on {doctype}")
        if not dry_run:
            for table in ("Custom DocPerm", "DocPerm"):
                for nm in frappe.db.get_all(table, filters={"parent": doctype, "role": "Instructor"}, pluck="name"):
                    frappe.delete_doc(table, nm, ignore_permissions=True, force=True)

    # 2. permission queries ------------------------------------------------
    log.append("\n--- Permission query scripts ---")
    for doctype, script in PERMISSION_QUERIES.items():
        log.append(_upsert_script(f"{doctype} Scope", "Permission Query", doctype, script, dry_run))

    # 3. homeroom write guards --------------------------------------------
    log.append("\n--- Homeroom write guards ---")
    for doctype in HOMEROOM_GUARDED_DOCTYPES:
        log.append(_upsert_script(
            f"{doctype} Homeroom Guard", "DocType Event", doctype,
            HOMEROOM_GUARD, dry_run, event="Before Save",
        ))

    # 4. reviewer anonymity ------------------------------------------------
    log.append("\n--- Teacher Evaluation reviewer anonymity ---")
    line = _reviewer_permlevel(dry_run)
    log.append(line or "  (already set)")

    # 5. role assignments --------------------------------------------------
    if destaff:
        log.append("\n--- Removing `Academics User` from linked teachers ---")
        targets = _teachers_to_destaff() + [
            u for u in EXTRA_DESTAFF if frappe.db.exists("Has Role", {"parent": u, "role": "Academics User"})
        ]
        log.append(f"  {len(targets)} accounts affected")
        for user in targets:
            log.append(f"    - {user}")
            if not dry_run:
                for nm in frappe.db.get_all("Has Role", filters={"parent": user, "role": "Academics User"}, pluck="name"):
                    frappe.delete_doc("Has Role", nm, ignore_permissions=True, force=True)

    if not dry_run:
        frappe.clear_cache()
        frappe.db.commit()
        log.append("\n=== committed, caches cleared ===")
    else:
        log.append("\n=== dry run complete, nothing written ===")

    out = "\n".join(log)
    print(out)
    return out
